# Project ki ek unique ID (Kujh bhi naam rakh sakte ho bina space ke)
sonar.projectKey=my-html-auto-deploy-project

# SonarQube dashboard par jo naam dikhega
sonar.projectName=HTML Auto Deploy Website

# Kaun sa code scan karna hai (. matlab poora folder)
sonar.sources=.