# Project ki unique ID
sonar.projectKey=my-html-auto-deploy-project

# SonarQube dashboard par jo naam dikhega
sonar.projectName=HTML Auto Deploy Website

# Organization ka naam (Kuch bhi dummy naam de do)
sonar.organization=my-local-org

# Kaun sa code scan karna hai (. matlab poora folder)
sonar.sources=.

# Local SonarQube server ka rasta (Docker internal networking ke liye)
sonar.host.url=http://host.docker.internal:9000